version: "3"

services:

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile

    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/workpacks
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo

  ws-server:
    build:
      context: ./ws-server
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"


  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8080:8081

