version: "3"

services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    volumes:
      - ./api-server:/opt/pdftron-collab-server/api-server
      - /opt/pdftron-collab-server/api-server/node_modules
    ports:
      - "3000:3000"
  ws-server:
    build:
      context: ./ws-server
      dockerfile: Dockerfile
    volumes:
      - ./ws-server:/opt/pdftron-collab-server/ws-server
      - /opt/pdftron-collab-server/ws-server/node_modules
    ports:
      - "4000:4000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/mgdata:/data/db
