version: "3"

services:
  ws-server:
    build:
      context: ./ws-server
      dockerfile: Dockerfile
    volumes:
      - ./ws-server:/opt/pdftron-collab-server/ws-server
      - /opt/pdftron-collab-server/ws-server/node_modules
    ports:
      - "4000:4000"
#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./.volumes/mgdata:/data/db
